### ISSUE TITLE
there is an error...

### ISSUE THREAD

**Issue by Redyoung49** [Dirkster99/Edi#53] opened 2019-08-16 04:10 UTC
I'm download the source code,run in vs2019 professional(16.1.3) ,and show a error like this...
 the theme is default(metro light) 
![Q9GXBVYV8}OV5D(MRY1 })V](https://user-images.githubusercontent.com/15117326/63142822-019b0800-c01e-11e9-8c44-384ee7a0a818.png)

I changed the theme to darklight.

Title: Unhandled Error
 Message: Object reference not set to an instance of an object.
 Help Link: https://github.com/Dirkster99/Edi/issues
Help Link Url: https://github.com/Dirkster99/Edi/issues
More Details: System.NullReferenceException: Object reference not set to an instance of an object.
   at Edi.App.OnStartup(StartupEventArgs e) in E:\工具\Edi-master\Edi\Edi\App.xaml.cs:line 242
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
![NZ~%62V@BBAI$E}C{~4YRZX](https://user-images.githubusercontent.com/15117326/63142705-6bff7880-c01d-11e9-9274-675234ce298b.png)

**Comment by Dirkster99** [comment] 2019-08-22 17:13
Hi Thanks, for reporting the issue.

I have downloaded the current master version from this [commit](https://github.com/Dirkster99/Edi/commit/82482687257a7e5e97405e47a2ff74895d7f02a3) and removed (for testing) all files at:

`C:\Users\<user>\AppData\Roaming\Edi`

Since the above directory stores config files and I wanted to simulate a first time run.

I Compiled and run the project in VS 2019 Community Edition **16.2.1** and cannot verify your exception.

Do I miss any condition to re-produce the problem?

Can you please try downloading the sources again and make sure that the above path (which stores configuration files) is empty?

I will, in the meantime update VS to **16.2.3**, to see if the problem might have been introduced with changes in VS.

**EDIT**
I updated to VS **16.2.3** but am still not able to verify the problem :-( The error message hints that the [output window cannot be resolved in App.xaml.cs at line 242](https://github.com/Dirkster99/Edi/blob/82482687257a7e5e97405e47a2ff74895d7f02a3/Edi/Edi/App.xaml.cs#L242).

But thats not making a lot of sense because:
- the container is configured in the [constructor](https://github.com/Dirkster99/Edi/blob/82482687257a7e5e97405e47a2ff74895d7f02a3/Edi/Edi/App.xaml.cs#L63).

- and the output window is registered in [App.xaml.cs Line 175](https://github.com/Dirkster99/Edi/blob/82482687257a7e5e97405e47a2ff74895d7f02a3/Edi/Edi/App.xaml.cs#L175)

So, the output window should be available in line 242 :-(

**Comment by Dirkster99** [comment] 2019-08-22 20:15
I did some more testing and ran into the same issue - the issue appeared for me when I did just a build not a *build all*. The problem is that **build** does **not** always build the output project, because VS thinks its not required since there is no direct dependency between Edi and the output project (but its loaded  on start-up but cannot be loaded if it is not present - I am adding a Debu.Assertion for this).

It is important to use the following steps to compile the project after downloading:

To simulate a fresh installation you may remove or rename: `C:\Users\<user>\AppData\Roaming\Edi`

- Right Click on Solution > Clean Solution (to initialize NuGet packages if they are missing)
- Right Click on Solution > Rebuild Solution
- Start Edi project

Does this work for you if you follow the workflow outlined above? I am pretty sure we can close this issue, right?

**Comment by Dirkster99** [comment] 2019-08-22 20:34
I have fixed the issue with this [commit](https://github.com/Dirkster99/Edi/commit/cb01dc99c6efbf5135300b8492da4e051b8e9850) to master. The solution is that you will get an assertion when you download the project and just select start (which will only build projects directly referenced by the Edi project).

![Assertion](https://user-images.githubusercontent.com/2129700/63547628-d5efb480-c52c-11e9-8de6-6df705f68db5.png)

From the Assertion dialog you can click on **Retry** to get to the source of the problem and hopefully some people will read the comment :-)
![Untitled1](https://user-images.githubusercontent.com/2129700/63547678-f455b000-c52c-11e9-9b0d-8426f90a90be.png)

**Closed as completed** 2019-08-23 17:23 UTC

**Comment by Redyoung49** [comment] 2019-10-16 10:58
thank you. 
it's work
